// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using liquidador_web.Data;

namespace liquidador_web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210704212312_CodigosDespacho")]
    partial class CodigosDespacho
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("liquidador_web.Models.Area", b =>
                {
                    b.Property<string>("codiarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("A069CODIAREA")
                        .HasMaxLength(4);

                    b.Property<string>("descarea")
                        .HasColumnName("A069DESCAREA")
                        .HasMaxLength(4);

                    b.HasKey("codiarea");

                    b.ToTable("T069BAAREAGENE");
                });

            modelBuilder.Entity("liquidador_web.Models.Auditoria", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("evento");

                    b.Property<DateTime>("fecha");

                    b.Property<string>("logActual");

                    b.Property<string>("logAnterior");

                    b.Property<string>("modulo");

                    b.Property<string>("usuarioId");

                    b.HasKey("ID");

                    b.HasIndex("usuarioId");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("liquidador_web.Models.Ciudad", b =>
                {
                    b.Property<string>("codiciud")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("A065CODICIUD")
                        .HasMaxLength(5);

                    b.Property<string>("descciud")
                        .HasColumnName("A065DESCCIUD")
                        .HasMaxLength(50);

                    b.HasKey("codiciud");

                    b.ToTable("T065BACIUDGENE");
                });

            modelBuilder.Entity("liquidador_web.Models.Clase", b =>
                {
                    b.Property<string>("codiclas")
                        .HasColumnName("A053CODICLAS")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("descclas")
                        .IsRequired()
                        .HasColumnName("A053DESCCLAS")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("codiclas");

                    b.ToTable("T053BACLASGENE");
                });

            modelBuilder.Entity("liquidador_web.Models.Dainfosuje", b =>
                {
                    b.Property<string>("numesuje")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("A102NUMESUJE")
                        .HasMaxLength(15);

                    b.Property<string>("ciu1suje")
                        .HasColumnName("A102CIU1SUJE")
                        .HasMaxLength(5);

                    b.Property<string>("ciu2suje")
                        .HasColumnName("A102CIU2SUJE")
                        .HasMaxLength(5);

                    b.Property<string>("ciudsuje")
                        .HasColumnName("A102CIUDSUJE")
                        .HasMaxLength(5);

                    b.Property<string>("dir1suje")
                        .HasColumnName("A102DIR1SUJE")
                        .HasMaxLength(200);

                    b.Property<string>("dir2suje")
                        .HasColumnName("A102DIR2SUJE")
                        .HasMaxLength(200);

                    b.Property<string>("docusuje")
                        .HasColumnName("A102DOCUSUJE")
                        .HasMaxLength(2);

                    b.Property<string>("fax1suje")
                        .HasColumnName("A102FAX1SUJE")
                        .HasMaxLength(30);

                    b.Property<string>("flagsanc")
                        .HasColumnName("A102FLAGSANC")
                        .HasMaxLength(2);

                    b.Property<string>("nombsuje")
                        .HasColumnName("A102NOMBSUJE")
                        .HasMaxLength(100);

                    b.Property<string>("provdefi")
                        .HasColumnName("A102PROVDEFI")
                        .HasMaxLength(1);

                    b.Property<string>("tarjprof")
                        .HasColumnName("A102TARJPROF")
                        .HasMaxLength(20);

                    b.Property<string>("tel1suje")
                        .HasColumnName("A102TEL1SUJE")
                        .HasMaxLength(30);

                    b.HasKey("numesuje");

                    b.ToTable("T102DAINFOSUJE");
                });

            modelBuilder.Entity("liquidador_web.Models.DataLiquidacion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("creadorId")
                        .IsRequired();

                    b.Property<string>("data")
                        .IsRequired();

                    b.Property<DateTime>("fecha");

                    b.Property<string>("llaveproc")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<int>("tipocodigo");

                    b.HasKey("ID");

                    b.HasIndex("creadorId");

                    b.HasIndex("tipocodigo");

                    b.ToTable("DataLiquidacion");
                });

            modelBuilder.Entity("liquidador_web.Models.Datasainte", b =>
                {
                    b.Property<int>("IDTasa")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("A921IDTasa")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Periodo")
                        .HasColumnName("A921Periodo")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("ResVigencia")
                        .HasColumnName("A921ResVigencia")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("TipoTasa")
                        .HasColumnName("A921TipoTasa")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<double?>("ValorTasa")
                        .HasColumnName("A921ValorTasa")
                        .HasColumnType("float");

                    b.Property<DateTime>("VigenteDesde")
                        .HasColumnName("A921VigenteDesde")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("VigenteHasta")
                        .HasColumnName("A921VigenteHasta")
                        .HasColumnType("datetime");

                    b.Property<int?>("importedID")
                        .HasColumnName("A921IDWebService");

                    b.HasKey("IDTasa");

                    b.HasIndex("importedID")
                        .IsUnique()
                        .HasFilter("[A921IDWebService] IS NOT NULL");

                    b.ToTable("T921DATASAINTE");
                });

            modelBuilder.Entity("liquidador_web.Models.Entidad", b =>
                {
                    b.Property<string>("codienti")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("A051CODIENTI")
                        .HasMaxLength(2);

                    b.Property<string>("descenti")
                        .HasColumnName("A051DESCENTI")
                        .HasMaxLength(50);

                    b.HasKey("codienti");

                    b.ToTable("T051BAENTIGENE");
                });

            modelBuilder.Entity("liquidador_web.Models.EntidadEspecialidad", b =>
                {
                    b.Property<string>("ciudad")
                        .HasColumnName("A081CODICIUD")
                        .HasMaxLength(5);

                    b.Property<string>("entidad")
                        .HasColumnName("A081CODIENTI")
                        .HasMaxLength(2);

                    b.Property<string>("especialidad")
                        .HasColumnName("A081CODIESPE")
                        .HasMaxLength(2);

                    b.Property<string>("despacho")
                        .HasColumnName("A081CODINUME")
                        .HasMaxLength(3);

                    b.Property<int>("consradi")
                        .HasColumnName("A081CONSRADI");

                    b.Property<string>("flagdesp")
                        .HasColumnName("A081FLAGDESP")
                        .HasMaxLength(2);

                    b.HasKey("ciudad", "entidad", "especialidad", "despacho");

                    b.ToTable("T081BRESPEENTI");
                });

            modelBuilder.Entity("liquidador_web.Models.Especialidad", b =>
                {
                    b.Property<string>("codiespe")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("A062CODIESPE")
                        .HasMaxLength(2);

                    b.Property<string>("descespe")
                        .HasColumnName("A062DESCESPE")
                        .HasMaxLength(50);

                    b.HasKey("codiespe");

                    b.ToTable("T062BAESPEGENE");
                });

            modelBuilder.Entity("liquidador_web.Models.Liquidaciones", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("autorId");

                    b.Property<DateTime>("fecha");

                    b.Property<string>("llaveprocA103llavproc");

                    b.Property<string>("nameFile");

                    b.Property<int?>("tipocodigo");

                    b.Property<string>("urlFile");

                    b.HasKey("ID");

                    b.HasIndex("autorId");

                    b.HasIndex("llaveprocA103llavproc");

                    b.HasIndex("tipocodigo");

                    b.ToTable("Liquidaciones");
                });

            modelBuilder.Entity("liquidador_web.Models.LiquidadorUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<bool>("Active");

                    b.Property<string>("CodDespacho");

                    b.Property<string>("CodEntidad");

                    b.Property<string>("CodEspecialidad");

                    b.Property<string>("CodLocalidad");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Creator");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FullName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<string>("Token");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("liquidador_web.Models.SubClase", b =>
                {
                    b.Property<string>("codisubc")
                        .HasColumnName("A071CODISUBC")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("descsubc")
                        .IsRequired()
                        .HasColumnName("A071DESCSUBC")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("codisubc");

                    b.ToTable("T071BASUBCGENE");
                });

            modelBuilder.Entity("liquidador_web.Models.T103dainfoproc", b =>
                {
                    b.Property<string>("A103llavproc")
                        .HasColumnName("A103LLAVPROC")
                        .HasMaxLength(23)
                        .IsUnicode(false);

                    b.Property<string>("A103anoradi")
                        .IsRequired()
                        .HasColumnName("A103ANORADI")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("A103anotactd")
                        .HasColumnName("A103ANOTACTD")
                        .HasMaxLength(1000)
                        .IsUnicode(false);

                    b.Property<string>("A103anotacts")
                        .HasColumnName("A103ANOTACTS")
                        .HasMaxLength(1000)
                        .IsUnicode(false);

                    b.Property<string>("A103anotorig")
                        .HasColumnName("A103ANOTORIG")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("A103ciudradi")
                        .IsRequired()
                        .HasColumnName("A103CIUDRADI")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("A103codiactd")
                        .HasColumnName("A103CODIACTD")
                        .HasMaxLength(8)
                        .IsUnicode(false);

                    b.Property<string>("A103codiacts")
                        .HasColumnName("A103CODIACTS")
                        .HasMaxLength(8)
                        .IsUnicode(false);

                    b.Property<string>("A103codiarea")
                        .IsRequired()
                        .HasColumnName("A103CODIAREA")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("A103codiciuo")
                        .IsRequired()
                        .HasColumnName("A103CODICIUO")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("A103codiclas")
                        .IsRequired()
                        .HasColumnName("A103CODICLAS")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("A103codiento")
                        .IsRequired()
                        .HasColumnName("A103CODIENTO")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("A103codiespo")
                        .IsRequired()
                        .HasColumnName("A103CODIESPO")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("A103codiinst")
                        .HasColumnName("A103CODIINST")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("A103codinatu")
                        .HasColumnName("A103CODINATU")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("A103codinumo")
                        .IsRequired()
                        .HasColumnName("A103CODINUMO")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<string>("A103codipadd")
                        .HasColumnName("A103CODIPADD")
                        .HasMaxLength(8)
                        .IsUnicode(false);

                    b.Property<string>("A103codipads")
                        .HasColumnName("A103CODIPADS")
                        .HasMaxLength(8)
                        .IsUnicode(false);

                    b.Property<string>("A103codipone")
                        .HasColumnName("A103CODIPONE")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("A103codiproc")
                        .IsRequired()
                        .HasColumnName("A103CODIPROC")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("A103codiproo")
                        .HasColumnName("A103CODIPROO")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("A103codirama")
                        .HasColumnName("A103CODIRAMA")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("A103codirecu")
                        .IsRequired()
                        .HasColumnName("A103CODIRECU")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("A103codisubc")
                        .IsRequired()
                        .HasColumnName("A103CODISUBC")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("A103codiubic")
                        .HasColumnName("A103CODIUBIC")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("A103codiusua")
                        .HasColumnName("A103CODIUSUA")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<int?>("A103consnorm")
                        .HasColumnName("A103CONSNORM");

                    b.Property<string>("A103consproc")
                        .IsRequired()
                        .HasColumnName("A103CONSPROC")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("A103cuadproc")
                        .HasColumnName("A103CUADPROC")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("A103cuadprod")
                        .HasColumnName("A103CUADPROD")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("A103cuadpros")
                        .HasColumnName("A103CUADPROS")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("A103descactd")
                        .HasColumnName("A103DESCACTD")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<string>("A103descacts")
                        .HasColumnName("A103DESCACTS")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<string>("A103entiradi")
                        .IsRequired()
                        .HasColumnName("A103ENTIRADI")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("A103esperadi")
                        .IsRequired()
                        .HasColumnName("A103ESPERADI")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<DateTime?>("A103fechdesd")
                        .HasColumnName("A103FECHDESD")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("A103fechdess")
                        .HasColumnName("A103FECHDESS")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("A103fechfind")
                        .HasColumnName("A103FECHFIND")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("A103fechfins")
                        .HasColumnName("A103FECHFINS")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("A103fechinid")
                        .HasColumnName("A103FECHINID")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("A103fechinis")
                        .HasColumnName("A103FECHINIS")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("A103fechorig")
                        .HasColumnName("A103FECHORIG")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("A103fechpres")
                        .HasColumnName("A103FECHPRES")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("A103fechproc")
                        .HasColumnName("A103FECHPROC")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("A103fechregi")
                        .HasColumnName("A103FECHREGI")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("A103fechrepa")
                        .HasColumnName("A103FECHREPA")
                        .HasColumnType("datetime");

                    b.Property<string>("A103flagcicd")
                        .HasColumnName("A103FLAGCICD")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("A103flagcics")
                        .HasColumnName("A103FLAGCICS")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("A103flagdete")
                        .HasColumnName("A103FLAGDETE")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<bool?>("A103flagproc")
                        .HasColumnName("A103FLAGPROC");

                    b.Property<string>("A103flagrepa")
                        .HasColumnName("A103FLAGREPA")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("A103flagvige")
                        .HasColumnName("A103FLAGVIGE")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("A103foliproc")
                        .HasColumnName("A103FOLIPROC")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.Property<string>("A103foliprod")
                        .HasColumnName("A103FOLIPROD")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.Property<string>("A103folipros")
                        .HasColumnName("A103FOLIPROS")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.Property<string>("A103horaproc")
                        .HasColumnName("A103HORAPROC")
                        .HasMaxLength(8)
                        .IsUnicode(false);

                    b.Property<string>("A103horaregi")
                        .HasColumnName("A103HORAREGI")
                        .HasMaxLength(8)
                        .IsUnicode(false);

                    b.Property<string>("A103horarepa")
                        .HasColumnName("A103HORAREPA")
                        .HasMaxLength(8)
                        .IsUnicode(false);

                    b.Property<string>("A103magiapro")
                        .HasColumnName("A103MAGIAPRO")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("A103nombpone")
                        .HasColumnName("A103NOMBPONE")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("A103nuenradi")
                        .IsRequired()
                        .HasColumnName("A103NUENRADI")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<string>("A103numeofic")
                        .HasColumnName("A103NUMEOFIC")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("A103numeproc")
                        .IsRequired()
                        .HasColumnName("A103NUMEPROC")
                        .HasMaxLength(21)
                        .IsUnicode(false);

                    b.Property<string>("A103numeradi")
                        .IsRequired()
                        .HasColumnName("A103NUMERADI")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.HasKey("A103llavproc");

                    b.HasIndex("A103codiproc");

                    b.HasIndex("A103codisubc");

                    b.HasIndex("A103numeproc")
                        .HasName("T103DAINFOPROC9");

                    b.HasIndex("A103numeradi", "A103nuenradi")
                        .HasName("T103DAINFOPROC7");

                    b.HasIndex("A103flagrepa", "A103ciudradi", "A103entiradi", "A103esperadi", "A103nuenradi")
                        .HasName("T103DAINFOPROC10");

                    b.HasIndex("A103codiclas", "A103llavproc", "A103ciudradi", "A103entiradi", "A103esperadi", "A103nuenradi", "A103anoradi", "A103numeradi", "A103flagrepa")
                        .HasName("T103DAINFOPROC19");

                    b.HasIndex("A103llavproc", "A103ciudradi", "A103entiradi", "A103esperadi", "A103nuenradi", "A103codiciuo", "A103codiento", "A103codiespo", "A103flagrepa", "A103consproc", "A103anoradi", "A103numeradi", "A103codinumo", "A103nombpone")
                        .HasName("T103DAINFOPROC15");

                    b.ToTable("T103DAINFOPROC");
                });

            modelBuilder.Entity("liquidador_web.Models.T112drsujeproc", b =>
                {
                    b.Property<string>("A112llavproc")
                        .HasColumnName("A112LLAVPROC")
                        .HasMaxLength(23)
                        .IsUnicode(false);

                    b.Property<string>("A112numesuje")
                        .HasColumnName("A112NUMESUJE")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("A112codisuje")
                        .HasColumnName("A112CODISUJE")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("A112cargo")
                        .HasColumnName("A112CARGO")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("A112ciudsuje")
                        .HasColumnName("A112CIUDSUJE")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("A112codicarc")
                        .HasColumnName("A112CODICARC")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("A112codiciu1")
                        .HasColumnName("A112CODICIU1")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("A112codiciud")
                        .HasColumnName("A112CODICIUD")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("A112codidocu")
                        .HasColumnName("A112CODIDOCU")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("A112codienti")
                        .HasColumnName("A112CODIENTI")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("A112codiespe")
                        .HasColumnName("A112CODIESPE")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("A112codinume")
                        .HasColumnName("A112CODINUME")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<string>("A112codisanc")
                        .HasColumnName("A112CODISANC")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("A112codisanp")
                        .HasColumnName("A112CODISANP")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("A112consproc")
                        .IsRequired()
                        .HasColumnName("A112CONSPROC")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("A112direccio")
                        .HasColumnName("A112DIRECCIO")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime?>("A112fechfina")
                        .HasColumnName("A112FECHFINA")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("A112fechinic")
                        .HasColumnName("A112FECHINIC")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("A112fechterm")
                        .HasColumnName("A112FECHTERM")
                        .HasColumnType("datetime");

                    b.Property<string>("A112flagdete")
                        .HasColumnName("A112FLAGDETE")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("A112flagexcl")
                        .HasColumnName("A112FLAGEXCL")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("A112flagreha")
                        .HasColumnName("A112FLAGREHA")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("A112flagrevo")
                        .HasColumnName("A112FLAGREVO")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("A112flagterm")
                        .HasColumnName("A112FLAGTERM")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("A112funcabog")
                        .HasColumnName("A112FUNCABOG")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("A112idenrepr")
                        .HasColumnName("A112IDENREPR")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("A112nombrepr")
                        .HasColumnName("A112NOMBREPR")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("A112nombsuje")
                        .IsRequired()
                        .HasColumnName("A112NOMBSUJE")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int?>("A112numeanop")
                        .HasColumnName("A112NUMEANOP");

                    b.Property<int?>("A112numeanos")
                        .HasColumnName("A112NUMEANOS");

                    b.Property<int?>("A112numediap")
                        .HasColumnName("A112NUMEDIAP");

                    b.Property<int?>("A112numedias")
                        .HasColumnName("A112NUMEDIAS");

                    b.Property<int?>("A112numemese")
                        .HasColumnName("A112NUMEMESE");

                    b.Property<int?>("A112numemesp")
                        .HasColumnName("A112NUMEMESP");

                    b.Property<string>("A112numeproc")
                        .IsRequired()
                        .HasColumnName("A112NUMEPROC")
                        .HasMaxLength(21)
                        .IsUnicode(false);

                    b.Property<string>("A112obseterm")
                        .HasColumnName("A112OBSETERM")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.Property<string>("A112telefono")
                        .HasColumnName("A112TELEFONO")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("A112llavproc", "A112numesuje", "A112codisuje");

                    b.HasIndex("A112codisuje")
                        .HasName("T112DRSUJEPROC20");

                    b.HasIndex("A112codisuje", "A112llavproc", "A112numesuje", "A112nombsuje")
                        .HasName("T112DRSUJEPROC12");

                    b.ToTable("T112DRSUJEPROC");
                });

            modelBuilder.Entity("liquidador_web.Models.T926liquidaciones1", b =>
                {
                    b.Property<string>("A926FECELABORA")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("A926FECELABORA");

                    b.Property<string>("A926CODUSUARIO")
                        .HasColumnName("A926CODUSUARIO")
                        .HasMaxLength(4);

                    b.Property<int>("A926CONSLIQ")
                        .HasColumnName("A926CONSLIQ")
                        .HasColumnType("int");

                    b.Property<string>("A926LIQUIDACION")
                        .HasColumnName("A926LIQUIDACION")
                        .HasColumnType("ntext");

                    b.Property<string>("A926LLAVPROC")
                        .HasColumnName("A926LLAVPROC")
                        .HasMaxLength(23);

                    b.Property<string>("A926TIPOLIQ")
                        .HasColumnName("A926TIPOLIQ")
                        .HasMaxLength(3);

                    b.HasKey("A926FECELABORA");

                    b.ToTable("T926LIQUIDACIONES1");
                });

            modelBuilder.Entity("liquidador_web.Models.TipoArea", b =>
                {
                    b.Property<string>("CODIAREA")
                        .HasColumnName("A090CODIAREA")
                        .HasMaxLength(4);

                    b.Property<string>("CODIPROC")
                        .HasColumnName("A090CODIPROC")
                        .HasMaxLength(4);

                    b.HasKey("CODIAREA", "CODIPROC");

                    b.ToTable("T090BRPROCAREA");
                });

            modelBuilder.Entity("liquidador_web.Models.TipoAreaClase", b =>
                {
                    b.Property<string>("codiarea")
                        .HasColumnName("A091CODIAREA")
                        .HasMaxLength(4);

                    b.Property<string>("codiclas")
                        .HasColumnName("A091CODICLAS")
                        .HasMaxLength(4);

                    b.Property<string>("codiproc")
                        .HasColumnName("A091CODIPROC")
                        .HasMaxLength(4);

                    b.HasKey("codiarea", "codiclas", "codiproc");

                    b.ToTable("T091BRCLASPROC");
                });

            modelBuilder.Entity("liquidador_web.Models.TipoAreaSubClase", b =>
                {
                    b.Property<string>("codiarea")
                        .HasColumnName("A092CODIAREA")
                        .HasMaxLength(4);

                    b.Property<string>("codiclas")
                        .HasColumnName("A092CODICLAS")
                        .HasMaxLength(4);

                    b.Property<string>("codiproc")
                        .HasColumnName("A092CODIPROC")
                        .HasMaxLength(4);

                    b.Property<string>("codisubc")
                        .HasColumnName("A092CODISUBC")
                        .HasMaxLength(4);

                    b.HasKey("codiarea", "codiclas", "codiproc", "codisubc");

                    b.ToTable("T092BRSUBCCLAS");
                });

            modelBuilder.Entity("liquidador_web.Models.TipoLiquidacion", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("A927CODTIPO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombre")
                        .HasColumnName("A927NOMBRET");

                    b.HasKey("codigo");

                    b.ToTable("T927TIPOLIQUID");
                });

            modelBuilder.Entity("liquidador_web.Models.TipoProceso", b =>
                {
                    b.Property<string>("codiproc")
                        .HasColumnName("A052CODIPROC")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("descproc")
                        .IsRequired()
                        .HasColumnName("A052DESCPROC")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("codiproc");

                    b.ToTable("T052BAPROCGENE");
                });

            modelBuilder.Entity("liquidador_web.Models.TiposPeriodo", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnName("A923IDTipoPeriodo");

                    b.Property<string>("Nombre")
                        .HasColumnName("A923NomTipoPeriodo");

                    b.HasKey("ID");

                    b.ToTable("T923TIPOSPERIODO");
                });

            modelBuilder.Entity("liquidador_web.Models.TiposTasas", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnName("A922IDTasa");

                    b.Property<string>("Nombre")
                        .HasColumnName("A922NomTasa");

                    b.HasKey("ID");

                    b.ToTable("T922TIPOSTASA");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("liquidador_web.Models.Auditoria", b =>
                {
                    b.HasOne("liquidador_web.Models.LiquidadorUser", "usuario")
                        .WithMany("Auditoria")
                        .HasForeignKey("usuarioId");
                });

            modelBuilder.Entity("liquidador_web.Models.DataLiquidacion", b =>
                {
                    b.HasOne("liquidador_web.Models.LiquidadorUser", "creador")
                        .WithMany()
                        .HasForeignKey("creadorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("liquidador_web.Models.TipoLiquidacion", "tipo")
                        .WithMany("Guardadas")
                        .HasForeignKey("tipocodigo")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("liquidador_web.Models.Liquidaciones", b =>
                {
                    b.HasOne("liquidador_web.Models.LiquidadorUser", "autor")
                        .WithMany("Liquidaciones")
                        .HasForeignKey("autorId");

                    b.HasOne("liquidador_web.Models.T103dainfoproc", "llaveproc")
                        .WithMany()
                        .HasForeignKey("llaveprocA103llavproc");

                    b.HasOne("liquidador_web.Models.TipoLiquidacion", "tipo")
                        .WithMany("Liquidaciones")
                        .HasForeignKey("tipocodigo");
                });

            modelBuilder.Entity("liquidador_web.Models.T103dainfoproc", b =>
                {
                    b.HasOne("liquidador_web.Models.Clase", "A103codiclasNavigation")
                        .WithMany("T103dainfoproc")
                        .HasForeignKey("A103codiclas")
                        .HasConstraintName("FRK07_T103DAINFOPROC");

                    b.HasOne("liquidador_web.Models.TipoProceso", "A103codiprocNavigation")
                        .WithMany("T103dainfoproc")
                        .HasForeignKey("A103codiproc")
                        .HasConstraintName("FRK06_T103DAINFOPROC");

                    b.HasOne("liquidador_web.Models.SubClase", "A103codisubcNavigation")
                        .WithMany("T103dainfoproc")
                        .HasForeignKey("A103codisubc")
                        .HasConstraintName("FRK08_T103DAINFOPROC");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("liquidador_web.Models.LiquidadorUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("liquidador_web.Models.LiquidadorUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("liquidador_web.Models.LiquidadorUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("liquidador_web.Models.LiquidadorUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
